"""Report language: the English message catalog, the loader, the translator.

Every user-facing string the report and the chart print -- headings, table
headers, captions, the headline sentence, assumptions and limitations -- is
declared in :data:`MESSAGES` as an **English template keyed by a stable id**.

To produce a report in *any* language, an agent writes a JSON file that maps
each id to that language's wording (the English template is the reference:
translate the words, keep the ids and the ``{placeholders}``) and renders with
``--report-lang <code>``. Nothing is machine-translated inside the skill, so a
translation can never be invented silently.

What this module guarantees:

* an id that is not in :data:`MESSAGES` raises ``KeyError`` -- a typo fails
  loudly instead of printing English nobody checked;
* a translation whose ``{placeholders}`` differ from the English template is
  **rejected** (recorded as invalid) and the English text is used instead, so
  a dropped ``{count}`` cannot produce ``"shown: "`` ;
* every fallback is recorded and *reported*: :meth:`Translator.note` renders a
  visible note for the report, :func:`warn_untranslated` prints the full id
  list to stderr.

Data is never translated: numbers, month labels, language codes, article
titles, Q-ids and message ids are passed in already formatted by the stage
that computed them.
"""

from __future__ import annotations

import json
import string
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, TextIO, cast

from payloads import MessageRef

ENGLISH = "en"

#: Key a list parameter is joined with unless the parameter says otherwise.
DEFAULT_SEP = "join.comma"

REFERENCE_INSTRUCTIONS = (
    "Translate every value in \"messages\" into {lang}. Keep the keys, every "
    "{{placeholder}} name, and any ids, file paths (references/methods.md), "
    "URLs, licence names (CC0 1.0) and numbers exactly as written. Then rerun "
    "with --report-lang {lang}."
)


# --------------------------------------------------------------------------
# The English source of every string the reader sees
# --------------------------------------------------------------------------
MESSAGES: dict[str, str] = {
    # --- report: shared presentation -------------------------------------
    "report.title": "Audience interest: {topic}",
    "report.subtitle": (
        "{langs} \u00b7 {since} to {until} ({months} months) \u00b7 "
        "access={access}, agent={agent} \u00b7 generated {generated}"
    ),
    "report.no_data": "no data",
    "report.unresolved": "unresolved",
    "report.footer": (
        "Data: Wikimedia Page view analytics (CC0 1.0). "
        "Methods, thresholds and their rationale: references/methods.md. "
        "Topic concept: {qid}. Generated by wikipedia-interest-analyzer."
    ),
    # --- report: table ----------------------------------------------------
    "report.col_lang": "Lang",
    "report.col_article": "Article",
    "report.col_views": "Views",
    "report.col_share": "Share/M",
    "report.col_yoy_abs": "YoY abs",
    "report.col_yoy_share": "YoY share",
    "report.col_r2": "R\u00b2",
    "report.col_confidence": "Confidence",
    "report.gap_article": "no article exists",
    "report.gap_confidence": "not measurable",
    "report.na": "n/a",
    "confidence.high": "high",
    "confidence.medium": "medium",
    "confidence.low": "low",
    # --- report: verdict, gaps, caveats -----------------------------------
    "report.gaps_note": (
        "No article exists in: {langs} \u2014 reported as a coverage gap, "
        "never replaced by a substitute."
    ),
    "caveat.warning": "Warning: {item}",
    "report.assumptions_heading": "Assumptions & limitations",
    # --- report: chart embedding -----------------------------------------
    "report.chart_alt": "Pageview comparison chart",
    "report.chart_caption": (
        "Absolute monthly pageviews (top) and normalised share of all wiki "
        "pageviews (bottom)."
    ),
    "report.chart_missing": "Chart unavailable (no series to plot).",
    "report.figure_caption": (
        "Figure: absolute monthly pageviews (top) and normalised share of all "
        "wiki pageviews (bottom)."
    ),
    # --- chart ------------------------------------------------------------
    "chart.views_ylabel": "views / month",
    "chart.views_title": "Absolute monthly pageviews",
    "chart.share_ylabel": "per million project views",
    "chart.share_title": "Normalised share of all wiki pageviews",
    "chart.xlabel": "month",
    "chart.suptitle": "{topic}  ({since} .. {until}, {months} months)",
    "chart.gaps_note": "no article in: {langs}",
    "chart.legend_entry": "{lang}: {title}",
    # --- analysis: headline ------------------------------------------------
    "headline.none": (
        "No language edition has enough data to assess interest in {topic} "
        "over {span}."
    ),
    "headline.main": (
        "Normalised interest in {topic} over {span} (second half vs first "
        "half): {parts}. Confidence: {grades}."
    ),
    "headline.part": "{lang} {share_pct} share ({article_pct} absolute)",
    "headline.part_na": "{lang} n/a",
    "headline.grade": "{lang} {confidence}",
    "headline.substitute": "{lang} uses '{title}' (no native article exists)",
    "headline.substitutes": "Substitute in use: {items}.",
    "headline.gaps": "No article exists in: {langs} -- not measurable.",
    # --- analysis: assumptions ---------------------------------------------
    "assumption.share": (
        "Share = article views / total project views x 1e6; growth counts "
        "only when absolute and normalised direction agree."
    ),
    "assumption.thresholds": (
        "Confidence thresholds (R2 0.6/0.4, seasonality 2x, 24 months, 50 "
        "views/month) are design parameters, tuned on recorded fixtures."
    ),
    # --- analysis: limitations ---------------------------------------------
    "limitation.pageviews": (
        "Pageviews measure article reads, not willingness to pay -- treat "
        "this as a direction indicator, not a market size."
    ),
    "limitation.proxy": (
        "Interest is proxied by one article per language edition; how much of "
        "the topic each article covers can differ between editions."
    ),
    "limitation.requests": (
        "Requests used access={access}, agent={agent} (bots excluded); "
        "Wikimedia rate limits were not probed, so requests are sequential "
        "with a fixed delay."
    ),
    "limitation.growth": (
        "Growth compares the second half of the window with the first half "
        "(design choice; see references/methods.md)."
    ),
    "limitation.gaps": (
        "No Wikipedia article exists for this topic in: {langs}. Coverage "
        "gaps are reported, never filled with a substitute article."
    ),
    "limitation.substitutes": (
        "Manual substitution in effect: {items}. A substitute may cover a "
        "broader or different scope than the topic, so cross-language "
        "comparisons involving it are not like-for-like."
    ),
    "limitation.substitute_item": "{lang} = '{title}' ({reason})",
    "limitation.reason_native": "no native article exists for this topic",
    "limitation.reason_chosen": "chosen explicitly",
    "limitation.seasonal": (
        "Seasonal signal detected -- {items}. A single seasonal cycle can "
        "dominate a short window."
    ),
    "limitation.seasonal_item": (
        "{lang} peaks in calendar month {month} ({ratio}x the overall mean)"
    ),
    # --- joins and the fallback note ---------------------------------------
    "join.comma": ", ",
    "join.semicolon": "; ",
    "i18n.note": (
        "Untranslated text: {count} of {total} report strings are shown in "
        "English because {lang} has no translation for them ({keys})."
    ),
}


def placeholders(template: str) -> set[str]:
    """The ``{name}`` fields a template expects (conversion/spec stripped).

    Args:
        template: An English or translated template string.

    Returns:
        The set of field names, e.g. ``{"topic", "span"}``.

    Raises:
        ValueError: If the braces are unbalanced -- callers treat that as a
            malformed translation rather than crashing on it.
    """
    names: set[str] = set()
    for _, field, _, _ in string.Formatter().parse(template):
        if field:
            names.add(field.split(".")[0].split("[")[0])
    return names


def normalize_lang(lang: str | None) -> str:
    """Canonical language code: trimmed, lowercased, empty means English."""
    code = (lang or "").strip().lower()
    return code or ENGLISH


# --------------------------------------------------------------------------
# Translator
# --------------------------------------------------------------------------
class Translator:
    """Renders message refs in one language, recording every English fallback.

    Args:
        lang: Target language code; ``"en"`` means "no translation needed".
        messages: id -> translated template. Unknown ids are kept in
            :attr:`ignored` rather than raising, because a translations file
            may legitimately carry notes of its own.
        malformed: Ids whose value was not a string (recorded, not rendered).
    """

    def __init__(
        self,
        lang: str,
        messages: Mapping[str, str] | None = None,
        *,
        malformed: Sequence[str] = (),
    ) -> None:
        """Set up the language and split supplied ids into known/unknown."""
        self.lang = normalize_lang(lang)
        supplied = dict(messages or {})
        self._translations = {k: v for k, v in supplied.items() if k in MESSAGES}
        self.ignored = sorted(str(k) for k in supplied if k not in MESSAGES)
        self.malformed = sorted(str(k) for k in malformed)
        self._missing: set[str] = set()
        self._invalid: set[str] = set()
        self.used: set[str] = set()

    @property
    def is_english(self) -> bool:
        """True when no translation is in play (English needs no fallbacks)."""
        return self.lang == ENGLISH

    @property
    def display_lang(self) -> str:
        """The language the rendered text is actually in (for ``<html lang>``).

        A missing translations file leaves the report fully English even
        though ``lang`` names the *requested* language -- tagging that as
        ``pl`` would misdescribe the document to screen readers and to
        anyone importing it.
        """
        if self.is_english or self._translations:
            return self.lang
        return ENGLISH

    @property
    def untranslated(self) -> list[str]:
        """Ids that rendered in English instead of the requested language."""
        return sorted(self._missing | self._invalid)

    def t(self, key: str, /, **params: Any) -> str:
        """Format one message: the translation if it is sound, else English.

        Args:
            key: Message id; must exist in :data:`MESSAGES`.
            **params: Values for the template's placeholders.

        Returns:
            The formatted string, in ``lang`` when a valid translation exists.

        Raises:
            KeyError: If ``key`` is not a known message id -- a typo in the
                skill's own code, never a user error to hide.
        """
        try:
            template = MESSAGES[key]
        except KeyError:
            raise KeyError(
                f"unknown message id {key!r} -- it must be added to "
                "i18n.MESSAGES with its English text first"
            ) from None
        self.used.add(key)
        if self.is_english:
            return template.format(**params)

        translation = self._translations.get(key)
        if translation is None:
            self._missing.add(key)
            return template.format(**params)
        try:
            sound = placeholders(translation) == placeholders(template)
        except ValueError:
            # Unbalanced braces in the translation: unusable, same treatment.
            sound = False
        if not sound:
            self._invalid.add(key)
            return template.format(**params)
        try:
            return translation.format(**params)
        except (IndexError, KeyError, TypeError, ValueError):
            # Right placeholders, wrong types (e.g. "{count:d}" on a string):
            # still a malformed translation, never a crash.
            self._invalid.add(key)
            return template.format(**params)

    def render(self, ref: MessageRef) -> str:
        """Render a message ref tree (see ``payloads.MessageRef``).

        A ref is either ``{"id", "params"}`` (format one message) or
        ``{"concat": [ref, ...]}`` (join rendered parts with a space, which is
        how the headline appends its optional sentences). A parameter may be a
        nested ref, a plain value, a list (joined with ``join.comma``) or
        ``{"items": [...], "sep": "<message id>"}`` for another separator.

        Args:
            ref: The tree stored in ``analysis.json``.

        Returns:
            The fully rendered string.

        Raises:
            TypeError: If a parameter dict has none of the recognised shapes
                -- a hand-edited payload, never something analyze.py writes.
        """
        concat = ref.get("concat")
        if concat is not None:
            return " ".join(self.render(part) for part in concat)
        key = ref.get("id")
        if not key:
            raise TypeError(f"message ref needs an 'id' or 'concat': {ref!r}")
        params = {
            name: self._value(value)
            for name, value in (ref.get("params") or {}).items()
        }
        return self.t(key, **params)

    def _value(self, value: Any) -> Any:
        """Resolve one parameter value: ref, group, list, or plain data."""
        if isinstance(value, dict):
            if "id" in value or "concat" in value:
                return self.render(cast(MessageRef, value))
            if "items" in value:
                sep = value.get("sep", DEFAULT_SEP)
                join = self.t(sep)
                return join.join(self._item(item) for item in value["items"])
            raise TypeError(
                "message parameter is a dict with no 'id', 'concat' or "
                f"'items': {value!r}"
            )
        if isinstance(value, list):
            join = self.t(DEFAULT_SEP)
            return join.join(self._item(item) for item in value)
        return value

    def _item(self, item: Any) -> str:
        """Render one element of a joined list (ref, group, or plain data)."""
        if isinstance(item, dict):
            if "id" in item or "concat" in item:
                return self.render(cast(MessageRef, item))
            if "items" in item:
                return str(self._value(item))
            raise TypeError(
                f"list item is a dict with no 'id', 'concat' or 'items': {item!r}"
            )
        return str(item)

    def mark_untranslated(self, key: str) -> None:
        """Record text that has no message id at all (an English-only payload).

        Used when a payload predates the ``*_i18n`` structures: the report
        still renders, but the note must admit that part of it is English.
        """
        if not self.is_english:
            self._missing.add(key)

    def note(self) -> str | None:
        """The visible "part of this report is English" note, or ``None``.

        Returns:
            ``None`` for English, or when every string was translated.
        """
        if self.is_english:
            return None
        keys = [key for key in self.untranslated if key != "i18n.note"]
        if not keys:
            return None
        shown = ", ".join(keys[:5])
        if len(keys) > 5:
            shown += f", +{len(keys) - 5} more"
        return self.t(
            "i18n.note",
            count=len(keys),
            total=max(len(self.used), len(keys)),
            lang=self.lang,
            keys=shown,
        )


def english() -> Translator:
    """The shared English translator (fallback path; records nothing)."""
    return _ENGLISH


_ENGLISH = Translator(ENGLISH)


# --------------------------------------------------------------------------
# Translations file
# --------------------------------------------------------------------------
def load_messages(path: Path) -> tuple[dict[str, str], list[str]]:
    """Read a translations file: ``{"messages": {id: text}}`` or a flat map.

    Args:
        path: File to read; a missing file yields ``( {}, [] )``.

    Returns:
        ``(messages, malformed)`` where ``malformed`` lists ids whose value
        was not a string (they fall back to English like a missing id).

    Raises:
        SystemExit: If the file exists but cannot be read or is not JSON --
            a corrupt file must stop the run, not silently go untranslated.
    """
    if not path.is_file():
        return {}, []
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"error: cannot read translations {path}: {exc}") from exc
    if not isinstance(raw, dict):
        raise SystemExit(
            f"error: translations {path} must be a JSON object mapping "
            "message ids to text"
        )
    block = raw.get("messages")
    source = block if isinstance(block, dict) else raw
    messages: dict[str, str] = {}
    malformed: list[str] = []
    for key, value in source.items():
        if isinstance(value, str):
            messages[str(key)] = value
        else:
            malformed.append(str(key))
    return messages, malformed


def write_reference(path: Path, lang: str, *, force: bool = False) -> bool:
    """Write the English reference file the agent translates in place.

    Args:
        path: Where to write (parents are created).
        lang: Target language, recorded in the file and its instructions.
        force: Overwrite an existing file instead of refusing.

    Returns:
        True if written, False when the file exists and ``force`` is off.

    Raises:
        SystemExit: When refusing to clobber an existing translations file.
    """
    if path.exists() and not force:
        raise SystemExit(
            f"error: {path} already exists (use --force to overwrite it)"
        )
    payload = {
        "lang": normalize_lang(lang),
        "_instructions": REFERENCE_INSTRUCTIONS.format(lang=normalize_lang(lang)),
        "messages": dict(MESSAGES),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return True


def translator_for(
    lang: str, path: Path, *, stream: TextIO | None = None
) -> Translator:
    """Build the translator for ``lang`` from ``path``, creating it if absent.

    A missing file is *not* an error: the English reference is written where
    the next run will find it, and this run falls back to English (the report
    then says so). A corrupt file still fails loudly -- see
    :func:`load_messages`.

    Args:
        lang: Target language code; English short-circuits everything.
        path: Expected translations file.
        stream: Where the instructions/warnings go (stderr by default). The
            default is resolved at call time so a redirected stderr (tests,
            ``2>`` capture) actually receives them.

    Returns:
        A :class:`Translator`, possibly recording fallbacks.
    """
    out = stream if stream is not None else sys.stderr
    code = normalize_lang(lang)
    if code == ENGLISH:
        return Translator(ENGLISH)
    if not path.is_file():
        write_reference(path, code)
        print(
            f"warning: no translations for '{code}' at {path}; wrote the "
            f"English reference file. Translate its \"messages\" values and "
            f"rerun with --report-lang {code}. Falling back to English for "
            "this run.",
            file=out,
        )
        return Translator(code)
    messages, malformed = load_messages(path)
    return Translator(code, messages, malformed=malformed)


def warn_untranslated(
    translator: Translator, *, stream: TextIO | None = None
) -> None:
    """Print every reason the output is not fully in ``lang`` (stderr).

    Nothing is printed for English or for a complete translation, so the
    normal run stays quiet.

    Args:
        translator: The translator whose fallbacks to report.
        stream: Where the warnings go (stderr by default, resolved at call
            time -- see :func:`translator_for`).
    """
    if translator.is_english:
        return
    out = stream if stream is not None else sys.stderr
    untranslated = translator.untranslated
    if untranslated:
        print(
            f"warning: {len(untranslated)} string(s) have no '{translator.lang}' "
            f"translation and were printed in English: "
            f"{', '.join(untranslated)}",
            file=out,
        )
    if translator.malformed:
        print(
            f"warning: non-string values in the translations file (treated as "
            f"missing): {', '.join(translator.malformed)}",
            file=out,
        )
    if translator.ignored:
        print(
            f"warning: unknown message ids in the translations file "
            f"(ignored): {', '.join(translator.ignored)}",
            file=out,
        )
